### ISSUE TITLE
scamp: amplitude skipping  should be avoided whe Time Grammar  is used

### ISSUE THREAD

**Issue by luca-s** [SeisComP/main#85] opened 2024-04-16 11:10 UTC
Dear developers,

I just wanted to report a possible issue in scmap. In particular scamp skips amplitude re-computations when the same pick id is used by multiple origins. However in SeisComP 6 the Time Grammar has been introduced and that makes the amplitude noise/signal windows dependent on the origin. That means the same pick id can produce multiple amplitude values , one for each origin the pick is referenced by.

This issue doesn't affect me since I am not using SeisComP v6 yet. I just wanted to make you aware of this (small?) issue.

Luca

**Comment by gempa-jabe** [comment] 2024-04-16 11:16
The time window only depends on the origin if a time definition depends on it. E.g. `signalBegin = 120` does not depend on the origin at all. It only means that if an origin is not present (scautopick amplitude calculations) then an origin dependent time window will cancel the amplitude computation.

In scamp an origin is always present but despite the fact that time windows are computed differently, another amplitude for the same pick won't be computed (although that issue must be tackled in the future).

Maybe I have overlooked something: where exactly did you spot potential or concrete issues?

**Comment by luca-s** [comment] 2024-04-16 11:22
> The time window only depends on the origin if a time definition depends on it.

I agree. I wrote "when Time Grammar is used" to simply.

> In scamp an origin is always present but despite the fact that time windows are computed differently, another amplitude for the same pick won't be computed (although that issue must be tackled in the future).

This is the issue (small?) I am referring to.

As long as you are aware of that you can close this issue.

**Comment by gempa-jabe** [comment] 2024-04-16 11:33
You mean that we now should produce multiple amplitude in scamp? That has been the case since ever. If the origin changes, time windows in scamp were also potentially changed due to the distance dependency in SC <= 5. The requirement is probably more visible now. If you are not using origin dependent time windows in SC 6 (default configuration), nothing compared to SC 5 changes. Do you agree?

**Comment by gempa-jabe** [comment] 2024-04-16 11:37
The issue is then with `scmag` which does not know which amplitude has been computed for which origin. An origin attribute is missing in the amplitude object. And even with this information it is not always necessary to recompute amplitudes and then it is even harder to pick an amplitude.

**Comment by luca-s** [comment] 2024-04-16 11:54
> If you are not using origin dependent time windows in SC 6 (default configuration), nothing compared to SC 5 changes. Do you agree?

Yes, I agree.

> The issue is then with scmag which does not know which amplitude has been computed for which origin. An origin attribute is missing in the amplitude object. And even with this information it is not always necessary to recompute amplitudes and then it is even harder to pick an amplitude.

You are right, it is more complex than I thought. I didn't think about scmag, but even in my original reasoning I was not sure this issue had to be fixed. I mostly wanted to report it and let you decide.

The scenario that made me open the issue is scanloc that generates multiple origin updates (scautoloc would be the same) and for each origin update scamp computes the amplitudes only for picks without an amplitude already associated to them.  That means each origin update has some amplitudes computed with time windows dependent on its own location and some other amplitudes  computed with time windows dependent on the location of previous origin updates.

**Comment by gempa-jabe** [comment] 2024-04-16 11:59
Great, then we are on the same page. You are right about `scamp` and the scenario your are describing is already the case with e.g. MLv. The end time is dependent on the distance to the origin by default. I will close this issue, thanks for reminding us. If you need further discussions on this topic, feel free to reopen it.

**Closed by gempa-jabe** 2024-04-16 11:59 UTC
